version: '3.7'

services:
  talkative:
    image: dockerproxy.popfr1.repos.tech.orange/alpine
    command: 'sh -c "while true; do echo \"[$$(date)] This is a spurious and useless message\"; sleep 2; done"'
    networks:
      - clusternetwork
    deploy:
      mode: replicated
      replicas: 2

  significant:
    image: dockerproxy.popfr1.repos.tech.orange/alpine
    command: 'sh -c "cpt=1; while true; do echo \"[$$(date)] Message #$$cpt:\"; echo \"  This is message number #$$cpt\"; cpt=$$((cpt+1)); sleep 10; done"'
    networks:
      - clusternetwork
    deploy:
      mode: replicated
      replicas: 2

networks:
  clusternetwork:
    external: true
