version: "3.7"

services:
  filebeat:
    image: dockerproxy.popfr1.repos.tech.orange/elastic/filebeat:8.10.3
    labels:
      co.elastic.logs/enabled: "false"
    networks:
      - clusternetwork
    environment:
      - max_procs=1
      - "node_name={{.Node.Hostname}}"
      - "node_id={{.Node.ID}}"
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - filebeat_registry:/usr/share/filebeat/data
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    configs:
      - source: filebeat
        target: /usr/share/filebeat/filebeat.yml
    deploy:
      mode: global

networks:
  clusternetwork:
    external: true

configs:
  filebeat:
    file: filebeat.yml

volumes:
  filebeat_registry:
    driver: 'local'
