version: '3.7'

services:
  observable:
    image: mchauvin/toolbox:0.8.1
    healthcheck:
      start_period: 180s
    networks:
      - clusternetwork
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "8080:8080"

networks:
  clusternetwork:
    external: true
