version: '3.7'
 
services:
  toolbox:
    image: dedicaas-virt-docker-stable.popfr1.repos.tech.orange/toolbox:${version}
    healthcheck:
      start_period: 180s
    environment:
      - "task_name={{.Service.Name}}.{{.Task.Slot}}"
      - "node_name={{.Node.Hostname}}"
      - "node_id={{.Node.ID}}"
      - "SHUTDOWN=graceful"
    networks:
      - clusternetwork
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=clusternetwork
        - traefik.docker.lbswarm=true
        - traefik.http.routers.toolbox-${color}-router.entrypoints=web
        - traefik.http.routers.toolbox-${color}-router.rule=PathPrefix(`/${context_path}`)
        - traefik.http.middlewares.toolbox-${color}-stripprefix.stripprefix.prefixes=/${context_path}
        - traefik.http.routers.toolbox-${color}-router.middlewares=toolbox-${color}-stripprefix
        - traefik.http.routers.toolbox-${color}-router.service=toolbox-${color}-service
        - traefik.http.services.toolbox-${color}-service.loadbalancer.server.port=8080
 
networks:
  clusternetwork:
    external: true
