version: '3.7'
 
services:
  toolbox:
    image: mchauvin/toolbox:${version}
    environment:
      - "task_name={{.Service.Name}}.{{.Task.Slot}}"
      - "node_name={{.Node.Hostname}}"
      - "node_id={{.Node.ID}}"
      - "SHUTDOWN=graceful"
    networks:
      - clusternetwork
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=clusternetwork
        - traefik.docker.lbswarm=true
        - traefik.http.routers.toolbox-${color}-router.entrypoints=web
        - traefik.http.routers.toolbox-${color}-router.rule=PathPrefix(`/toolbox`)
        - traefik.http.middlewares.toolbox-stripprefix.stripprefix.prefixes=/toolbox
        - traefik.http.routers.toolbox-${color}-router.middlewares=toolbox-stripprefix
        - traefik.http.routers.toolbox-${color}-router.service=toolbox-${color}-service
        - traefik.http.services.toolbox-${color}-service.loadbalancer.server.port=8080
        - traefik.http.routers.toolbox-${color}-router.priority=${priority}
 
networks:
  clusternetwork:
    external: true
